	var myChart = echarts.init(document.getElementById('main'));         
    var option = {
    title : {
        text: 'Entity Relationship',
        subtext: 'The relationship between the six types of entities',
        x:'right',
        y:'bottom'
    },
    tooltip : {
        trigger: 'item',
        formatter: '{a} : {b}'
    },
    toolbox: {
        show : true,
        feature : {
            restore : {show: true},
            magicType: {show: true, type: ['force', 'chord']},
            saveAsImage : {show: true}
        }
    },
    legend: {
        x: 'left',
        data:['Protein','DNA','RNA','virus','cell_line','cell_type']
    },
    series : [
        {
            type:'force',
            name : "",
            ribbonType: false,
            categories : [
                {
                    name: 'Protein'
                },
                {
                    name: 'DNA'
                },
                {
                    name:'RNA'
                }, 
                {
                    name:'virus'
                },
                {
                    name:'cell_line'
                },
                {
                    name:'cell_type'
                },
                
            ],
            itemStyle: {
                normal: {
                    label: {
                        show: true,
                        textStyle: {
                            color: '#333'
                        }
                    },
                    nodeStyle : {
                        brushType : 'both',
                        borderColor : 'rgba(255,215,0,0.4)',
                        borderWidth : 1
                    },
                    linkStyle: {
                        type: 'curve'
                    }
                },
                emphasis: {
                    label: {
                        show: false
                        // textStyle: null      
                    },
                    nodeStyle : {
                        //r: 30
                    },
                    linkStyle : {}
                }
            },
            useWorker: false,
            minRadius : 15,
            maxRadius : 25,
            gravity: 1.1,
            scaling: 1.1,
            roam: 'move',
            nodes:[
                //P D R V CL CT
                {category:0,name: 'ER ',value :25182},
                {category:5,name: 'breast cancer cells ',value :14445},
                {category:1,name: 'BRCA1 ',value :14106},
                {category:0,name: 'p53 ',value :13998},
                {category:5,name: 'tumor cells ',value :11746},
                {category:4,name: 'MCF-7 cells ',value :10885},
                {category:5,name: 'cancer cells ',value :10734},
                {category:0,name: 'Estrogen receptor ',value :10171},
                {category:0,name: 'MCF-7 ',value :8208},
                {category:0,name: 'EGFR ',value :6500},
                {category:5,name: 'human breast cancer cells ',value :5265},
                {category:0,name: 'bcl-2 ',value :5109},
                {category:4,name: 'breast cancer cell lines ',value :4986},
                {category:1,name: 'BRCA2 ',value :4183},
                {category:4,name: 'cell lines ',value :3640},
                {category:0,name: 'ErbB2 ',value :3276},
                {category:0,name: 'ERalpha ',value :2850},
                {category:0,name: 'BRCA2 ',value :2633},
                {category:0,name: 'VEGF ',value :2591},
                {category:0,name: 'epidermal growth factor receptor ',value :2475},
                {category:2,name: 'mRNA ',value :2353},
                {category:0,name: 'monoclonal antibodies ',value :2349},
                {category:0,name: 'BRCA1 ',value :2236},
                {category:0,name: 'estrogen receptors ',value :2174},
                {category:4,name: 'human breast cancer cell lines ',value :1973},
                {category:5,name: 'malignant cells ',value :1688},
                {category:0,name: 'MUC1 ',value :1658},
                {category:0,name: 'vascular endothelial growth factor ',value :1559},
                {category:4,name: 'MCF-7 ',value :1506},
                {category:5,name: 'lymphocytes ',value :1382},
                {category:0,name: 'ERbeta ',value :1226},
                {category:0,name: 'p53 protein ',value :1145},
                {category:0,name: 'c-Myc ',value :1120},
                {category:0,name: 'T47D ',value :1095},
                {category:5,name: 'stromal cells ',value :1069},
                {category:0,name: 'pS2 ',value :1054},
                {category:0,name: 'cytokine ',value :1051},
                {category:5,name: 'fibroblasts ',value :1048},
                {category:1,name: 'p53 gene ',value :940},
                {category:5,name: 'human cancer cells ',value :909},
                {category:4,name: 'tumor cell lines ',value :880},
                {category:5,name: 'carcinoma cells ',value :869},
                {category:0,name: 'Src ',value :862},
                {category:0,name: 'CEA ',value :846},
                {category:0,name: 'AhR ',value :819},
                {category:5,name: 'myoepithelial cells ',value :802},
                {category:0,name: 'Fas ',value :798},
                {category:5,name: 'breast tumor cells ',value :721},
                {category:1,name: 'tumor suppressor genes ',value :709},
                {category:4,name: 'human breast cancer cell line ',value :620},
                {category:0,name: 'mitogen-activated protein kinase ',value :598},
                {category:5,name: 'breast epithelial cells ',value :592},
                {category:1,name: 'c-myc ',value :584},
                {category:0,name: 'IL-10 ',value :583},
                {category:0,name: 'IL-4 ',value :548},
                {category:4,name: 'HeLa cells ',value :515},
                {category:5,name: 'human cells ',value :507},
                {category:0,name: 'Oestrogen receptors ',value :487},
                {category:4,name: 'human breast cancer cell line MCF-7 ',value :343},
                {category:0,name: 'growth factor ',value :320},
                {category:0,name: 'MAP kinase ',value :315},
                {category:0,name: 'CAT ',value :293},
                {category:0,name: 'BT-20 ',value :248},
                {category:5,name: 'B cells ',value :245},
                {category:0,name: 'topoisomerase II ',value :242},
                {category:5,name: 'normal epithelial cells ',value :238},
                {category:0,name: 'androgen receptors ',value :235},
                {category:0,name: 'glucocorticoid receptor ',value :234},
                {category:0,name: 'interferon-gamma ',value :232},
                {category:4,name: 'human cell lines ',value :228},
                {category:0,name: 'FGFR1 ',value :227},
                {category:0,name: 'growth factor receptor ',value :222},
                {category:0,name: 'CD8 ',value :208},
                {category:0,name: 'p73 ',value :205},
                {category:0,name: 'Grb2 ',value :203},
                {category:0,name: 'Src kinase ',value :191},
                {category:5,name: 'malignant epithelial cells ',value :176},
                {category:1,name: 'estrogen response element ',value :170},
                {category:4,name: 'breast tumor cell lines ',value :164},
                {category:4,name: 'transfected cells ',value :163},
                {category:4,name: 'cell line ',value :159},
                {category:5,name: 'cytotoxic T lymphocytes ',value :155},
                {category:4,name: 'lung cancer cell lines ',value :151},
                {category:0,name: 'RTKs ',value :145},
                {category:4,name: 'human breast carcinoma cell line ',value :139},
                {category:0,name: 'CA-125 ',value :139},
                {category:1,name: 'promoter regions ',value :132},
                {category:0,name: 'Fas ligand ',value :117},
                {category:0,name: 'wnt-1 ',value :112},
                {category:1,name: 'tumour suppressor gene ',value :110},
                {category:0,name: 'n-3 ',value :109},
                {category:0,name: 'phosphatase ',value :103},
                {category:0,name: 'NCI-H460 ',value :97},
                {category:4,name: 'Breast cancer cells ',value :96},
                {category:1,name: 'germline ',value :94},
                {category:0,name: 'glucocorticoid receptors ',value :91},
                {category:2,name: 'p53 mRNA ',value :87},
                {category:4,name: 'human breast tumor cell lines ',value :84},
                {category:0,name: 'estradiol receptors ',value :83},
                {category:5,name: 'eukaryotic cells ',value :82},
                {category:0,name: 'beta-galactosidase ',value :82},
                {category:0,name: 'moAB ',value :74},
                {category:0,name: 'C-terminal region ',value :74},
                {category:0,name: 'protein tyrosine kinase ',value :64},
                {category:2,name: 'ERalpha mRNA ',value :61},
                {category:0,name: 'antigens ',value :60},
                {category:0,name: 'PUFAs ',value :60},
                {category:0,name: 'transmembrane protein ',value :56},
                {category:0,name: 'estrogen-receptor ( ER ',value :56},
                {category:0,name: 'H460 ',value :54},
                {category:0,name: 'n-3 PUFAs ',value :54},
                {category:0,name: 'tyrosine phosphatase ',value :53},
                {category:4,name: 'human breast adenocarcinoma MCF-7 cells ',value :51},
                {category:0,name: 'FGF8 ',value :51},
                {category:0,name: 'interleukin-10 ',value :50},
                {category:1,name: 'tumor sites ',value :44},
                {category:0,name: 'GHRH ',value :44},
                {category:0,name: 'fibroblast growth factor receptor ',value :44},
                {category:0,name: 'chloramphenicol acetyltransferase ',value :42},
                {category:1,name: 'pS2 ',value :41},
                {category:0,name: 'DNase ',value :41},
                {category:5,name: 'MCF-7 cells ',value :38},
                {category:0,name: 'estrogen receptors alpha and beta ',value :34},
                {category:0,name: 'OCT ',value :31},
                {category:4,name: 'BT-20 ',value :30},
                {category:1,name: 'p73 gene ',value :29},
                {category:4,name: 'human breast cancer lines ',value :27},
                {category:0,name: 'anti-MUC1 antibodies ',value :27},
                {category:0,name: 'transcriptional activators ',value :27},
                {category:1,name: 'cDNA sequence ',value :26},
                {category:0,name: 'fibroblast growth factor 8 ',value :26},
                {category:5,name: 'Transfected cells ',value :24},
                {category:0,name: 'chimeric receptor ',value :22},
                {category:0,name: 'tumour antigens ',value :22},
                {category:0,name: 'beta-gal ',value :21},
                {category:0,name: 'Herpes simplex virus thymidine kinase ',value :20},
                {category:0,name: 'cytosol estrogen receptor ',value :19},
                {category:0,name: 'endogenous ER ',value :18},
                {category:1,name: 'marker gene ',value :18},
                {category:0,name: 'CHO ',value :18},
                {category:0,name: 'DO-1 ',value :18},
                {category:1,name: 'bcl-2 ',value :17},
                {category:5,name: 'reactive cells ',value :15},
                {category:1,name: 'P1 promoter ',value :13},
                {category:5,name: 'pituitary cells ',value :13},
                {category:5,name: 'FAs ',value :12},
                {category:0,name: 'FGF family ',value :12},
                {category:0,name: 'GH3 ',value :12},
                {category:1,name: 'MUC1 ',value :12},
                {category:1,name: 'ERBB2 ',value :11},
                {category:0,name: 'YACs ',value :11},
                {category:4,name: 'original cell line ',value :10},
                {category:1,name: 'ATM locus ',value :10},
                {category:4,name: 'human breast cancer cells ',value :9},
                {category:0,name: 'MCF ',value :8},
                {category:0,name: 'ER-DBD ',value :8},
                {category:1,name: 'tumor-specific promoter ',value :8},
                {category:4,name: 'Chinese hamster ovary ( CHO ) cells ',value :7},
                {category:4,name: 'T47D breast tumor cells ',value :6},
                {category:2,name: 'GRB2 mRNA ',value :6},
                {category:0,name: 'NSC-26271 ',value :6},
                {category:1,name: 'constitutive promoter ',value :6},
                {category:1,name: 'YACs ',value :5},
                {category:2,name: 'FGF8 mRNA ',value :5},
                {category:4,name: 'MCF-7 transfectants ',value :5},
                {category:0,name: 'cytoplasmic oestrogen receptors ',value :5},
                {category:0,name: 'BTC ',value :5},
                {category:1,name: 'ER-responsive reporter gene ',value :4},
                {category:0,name: 'NSC-123127 ',value :4},
                {category:1,name: 'n-3 PUFAs ',value :4},
                {category:1,name: 'progesterone receptor gene promoter ',value :3},
                {category:0,name: 'p73 LOH ',value :3},
                {category:1,name: 'estrogen receptor sites ',value :3},
                {category:5,name: 'Human B lymphocytes ',value :3},
                {category:0,name: 'ErbB2 receptor tyrosine kinases ',value :3},
                {category:4,name: 'H460 ',value :3},
                {category:4,name: 'human cancer cells ',value :2},
                {category:0,name: 'P1CAT ',value :2},
                {category:1,name: 'c-Myc responsive element ',value :2},
                {category:1,name: 'P1CAT reporter plasmid ',value :2},
                {category:1,name: 'Oct ',value :2},
                {category:4,name: 'nonpituitary cell line ',value :2},
                {category:4,name: 'normal human cell lines ',value :2},
                {category:0,name: 'zinc-finger proteins ',value :2},
                {category:1,name: 'GHRH gene ',value :2},
                {category:0,name: 'immunoreactive GHRH ',value :2},
                {category:4,name: 'serum-stimulated T47D cells ',value :1},

            ],
            links : [
{source: 'AhR ' ,target: 'estrogen-receptor ( ER ',weight :2,name: '2'},
{source: 'AhR ' ,target: 'human breast cancer cells ',weight :1,name: '1'},
{source: 'AhR ' ,target: 'progesterone receptor gene promoter ',weight :2,name: '2'},
{source: 'AhR ' ,target: 'promoter regions ',weight :2,name: '2'},
{source: 'AhR ' ,target: 'pS2 ',weight :2,name: '2'},
{source: 'androgen receptors ' ,target: 'estrogen receptors ',weight :1,name: '1'},
{source: 'anti-MUC1 antibodies ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'B cells ' ,target: 'anti-MUC1 antibodies ',weight :2,name: '2'},
{source: 'B cells ' ,target: 'Human B lymphocytes ',weight :1,name: '1'},
{source: 'B cells ' ,target: 'IL-10 ',weight :2,name: '2'},
{source: 'B cells ' ,target: 'IL-4 ',weight :2,name: '2'},
{source: 'B cells ' ,target: 'interleukin-10 ',weight :2,name: '2'},
{source: 'B cells ' ,target: 'tumour antigens ',weight :2,name: '2'},
{source: 'bcl-2 ' ,target: 'human breast adenocarcinoma MCF-7 cells ',weight :1,name: '1'},
{source: 'bcl-2 ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'bcl-2 ' ,target: 'MCF-7 cells ',weight :1,name: '1'},
{source: 'bcl-2 ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'bcl-2 ' ,target: 'p53 mRNA ',weight :1,name: '1'},
{source: 'bcl-2 ' ,target: 'protein tyrosine kinase ',weight :2,name: '2'},
{source: 'bcl-2 ' ,target: 'topoisomerase II ',weight :2,name: '2'},
{source: 'beta-gal ' ,target: 'GH3 ',weight :2,name: '2'},
{source: 'beta-gal ' ,target: 'herpes simplex virus thymidine kinase ',weight :1,name: '1'},
{source: 'beta-gal ' ,target: 'nonpituitary cell line ',weight :2,name: '2'},
{source: 'beta-gal ' ,target: 'T47D breast tumor cells ',weight :2,name: '2'},
{source: 'beta-galactosidase ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'beta-galactosidase ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'beta-galactosidase ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'BRCA1 ' ,target: 'BRCA2 ',weight :4,name: '4'},
{source: 'BRCA1 ' ,target: 'CA-125 ',weight :2,name: '2'},
{source: 'BRCA2 ' ,target: 'BRCA1 ',weight :2,name: '2'},
{source: 'BRCA2 ' ,target: 'CA-125 ',weight :1,name: '1'},
{source: 'BRCA2 ' ,target: 'tumor suppressor genes ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'FGF8 ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'FGF8 mRNA ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'fibroblast growth factor receptor ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'breast cancer cell lines ' ,target: 'malignant epithelial cells ',weight :2,name: '2'},
{source: 'breast cancer cells ' ,target: 'c-Myc ',weight :5,name: '5'},
{source: 'breast cancer cells ' ,target: 'c-Myc responsive element ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'breast cancer cells ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'EGFR ',weight :6,name: '6'},
{source: 'breast cancer cells ' ,target: 'epidermal growth factor receptor ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'ER ',weight :2,name: '2'},
{source: 'breast cancer cells ' ,target: 'ErbB2 ',weight :7,name: '7'},
{source: 'breast cancer cells ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'Grb2 ',weight :8,name: '8'},
{source: 'breast cancer cells ' ,target: 'GRB2 mRNA ',weight :2,name: '2'},
{source: 'breast cancer cells ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'MAP kinase ',weight :2,name: '2'},
{source: 'breast cancer cells ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'breast cancer cells ' ,target: 'mitogen-activated protein kinase ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'P1 promoter ',weight :4,name: '4'},
{source: 'breast cancer cells ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'P1CAT reporter plasmid ',weight :1,name: '1'},
{source: 'breast cancer cells ' ,target: 'p53 gene ',weight :4,name: '4'},
{source: 'breast cancer cells ' ,target: 'RTKs ',weight :4,name: '4'},
{source: 'breast cancer cells ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'breast epithelial cells ' ,target: 'DNase ',weight :1,name: '1'},
{source: 'breast epithelial cells ' ,target: 'eukaryotic cells ',weight :1,name: '1'},
{source: 'breast tumor cell lines ' ,target: 'breast tumor cells ',weight :1,name: '1'},
{source: 'breast tumor cell lines ' ,target: 'phosphatase ',weight :1,name: '1'},
{source: 'breast tumor cell lines ' ,target: 'Src ',weight :2,name: '2'},
{source: 'breast tumor cell lines ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'breast tumor cell lines ' ,target: 'tyrosine phosphatase ',weight :1,name: '1'},
{source: 'breast tumor cells ' ,target: 'breast tumor cell lines ',weight :1,name: '1'},
{source: 'breast tumor cells ' ,target: 'phosphatase ',weight :2,name: '2'},
{source: 'breast tumor cells ' ,target: 'Src ',weight :3,name: '3'},
{source: 'breast tumor cells ' ,target: 'Src kinase ',weight :1,name: '1'},
{source: 'breast tumor cells ' ,target: 'tumor cell lines ',weight :2,name: '2'},
{source: 'breast tumor cells ' ,target: 'tyrosine phosphatase ',weight :2,name: '2'},
{source: 'BT-20 ' ,target: 'chimeric receptor ',weight :1,name: '1'},
{source: 'BT-20 ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'BT-20 ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'BT-20 ' ,target: 'Fas ligand ',weight :3,name: '3'},
{source: 'BT-20 ' ,target: 'interferon-gamma ',weight :1,name: '1'},
{source: 'BTC ' ,target: 'transfected cells ',weight :2,name: '2'},
{source: 'c-Myc ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'c-Myc ' ,target: 'c-Myc responsive element ',weight :1,name: '1'},
{source: 'c-Myc ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'c-Myc ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'c-Myc ' ,target: 'ER ',weight :4,name: '4'},
{source: 'c-Myc ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'c-Myc ' ,target: 'P1 promoter ',weight :8,name: '8'},
{source: 'c-Myc ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'c-Myc ' ,target: 'P1CAT reporter plasmid ',weight :1,name: '1'},
{source: 'c-Myc ' ,target: 'p53 gene ',weight :6,name: '6'},
{source: 'c-Myc ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'c-Myc responsive element ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'c-Myc responsive element ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'c-Myc responsive element ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'c-Myc responsive element ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'c-Myc responsive element ' ,target: 'ER ',weight :2,name: '2'},
{source: 'c-Myc responsive element ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'c-Myc responsive element ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'c-Myc responsive element ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'c-Myc responsive element ' ,target: 'P1CAT reporter plasmid ',weight :1,name: '1'},
{source: 'c-Myc responsive element ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'c-Myc responsive element ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'C-terminal region ' ,target: 'p53 gene ',weight :1,name: '1'},
{source: 'C-terminal region ' ,target: 'p73 ',weight :2,name: '2'},
{source: 'C-terminal region ' ,target: 'p73 gene ',weight :1,name: '1'},
{source: 'cancer cells ' ,target: 'myoepithelial cells ',weight :1,name: '1'},
{source: 'cancer cells ' ,target: 'original cell line ',weight :1,name: '1'},
{source: 'cancer cells ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'carcinoma cells ' ,target: 'ERalpha ',weight :21,name: '21'},
{source: 'carcinoma cells ' ,target: 'ERalpha mRNA ',weight :5,name: '5'},
{source: 'carcinoma cells ' ,target: 'ERbeta ',weight :18,name: '18'},
{source: 'carcinoma cells ' ,target: 'stromal cells ',weight :1,name: '1'},
{source: 'CAT ' ,target: 'breast cancer cells ',weight :5,name: '5'},
{source: 'CAT ' ,target: 'c-Myc ',weight :20,name: '20'},
{source: 'CAT ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'CAT ' ,target: 'ER ',weight :10,name: '10'},
{source: 'CAT ' ,target: 'MCF-7 cells ',weight :6,name: '6'},
{source: 'CAT ' ,target: 'P1 promoter ',weight :15,name: '15'},
{source: 'CAT ' ,target: 'P1CAT ',weight :5,name: '5'},
{source: 'CAT ' ,target: 'p53 gene ',weight :10,name: '10'},
{source: 'CAT ' ,target: 'serum-stimulated T47D cells ',weight :4,name: '4'},
{source: 'CD8 ' ,target: 'BT-20 ',weight :1,name: '1'},
{source: 'CD8 ' ,target: 'chimeric receptor ',weight :1,name: '1'},
{source: 'CD8 ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'CD8 ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'CD8 ' ,target: 'Fas ligand ',weight :3,name: '3'},
{source: 'CD8 ' ,target: 'interferon-gamma ',weight :1,name: '1'},
{source: 'CD8 ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'CD8 ' ,target: 'T47D ',weight :1,name: '1'},
{source: 'cDNA sequence ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'cDNA sequence ' ,target: 'Chinese hamster ovary ( CHO ) cells ',weight :1,name: '1'},
{source: 'cDNA sequence ' ,target: 'human breast cancer cell line MCF-7 ',weight :1,name: '1'},
{source: 'cDNA sequence ' ,target: 'MCF-7 transfectants ',weight :1,name: '1'},
{source: 'cDNA sequence ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'cDNA sequence ' ,target: 'transmembrane protein ',weight :1,name: '1'},
{source: 'CEA ' ,target: 'Cea ',weight :1,name: '1'},
{source: 'cell line ' ,target: 'human breast carcinoma cell line ',weight :1,name: '1'},
{source: 'cell line ' ,target: 'human cell lines ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'androgen receptors ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'breast tumor cell lines ',weight :2,name: '2'},
{source: 'cell lines ' ,target: 'breast tumor cells ',weight :4,name: '4'},
{source: 'cell lines ' ,target: 'C-terminal region ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'estradiol receptors ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'estrogen receptor sites ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'estrogen receptors ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'germline ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'MCF ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'p53 gene ',weight :1,name: '1'},
{source: 'cell lines ' ,target: 'p73 ',weight :4,name: '4'},
{source: 'cell lines ' ,target: 'p73 gene ',weight :2,name: '2'},
{source: 'cell lines ' ,target: 'p73 LOH ',weight :2,name: '2'},
{source: 'cell lines ' ,target: 'phosphatase ',weight :2,name: '2'},
{source: 'cell lines ' ,target: 'Src ',weight :4,name: '4'},
{source: 'cell lines ' ,target: 'Src kinase ',weight :3,name: '3'},
{source: 'cell lines ' ,target: 'tumor cell lines ',weight :2,name: '2'},
{source: 'cell lines ' ,target: 'tyrosine phosphatase ',weight :2,name: '2'},
{source: 'chimeric receptor ' ,target: 'BT-20 ',weight :1,name: '1'},
{source: 'chimeric receptor ' ,target: 'CD8 ',weight :1,name: '1'},
{source: 'chimeric receptor ' ,target: 'cytokine ',weight :2,name: '2'},
{source: 'chimeric receptor ' ,target: 'Fas ',weight :4,name: '4'},
{source: 'chimeric receptor ' ,target: 'Fas ligand ',weight :6,name: '6'},
{source: 'chimeric receptor ' ,target: 'interferon-gamma ',weight :2,name: '2'},
{source: 'chimeric receptor ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'chimeric receptor ' ,target: 'T47D ',weight :1,name: '1'},
{source: 'Chinese hamster ovary ( CHO ) cells ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'Chinese hamster ovary ( CHO ) cells ' ,target: 'human breast cancer cell line MCF-7 ',weight :1,name: '1'},
{source: 'Chinese hamster ovary ( CHO ) cells ' ,target: 'MCF-7 transfectants ',weight :1,name: '1'},
{source: 'Chinese hamster ovary ( CHO ) cells ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'CAT ',weight :4,name: '4'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'ER ',weight :2,name: '2'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'chloramphenicol acetyltransferase ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'CHO ' ,target: 'endogenous ER ',weight :1,name: '1'},
{source: 'CHO ' ,target: 'ER ',weight :4,name: '4'},
{source: 'CHO ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'CHO ' ,target: 'MCF-7 cells ',weight :1,name: '1'},
{source: 'constitutive promoter ' ,target: 'beta-galactosidase ',weight :1,name: '1'},
{source: 'constitutive promoter ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'constitutive promoter ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'constitutive promoter ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'constitutive promoter ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'cytoplasmic oestrogen receptors ' ,target: 'oestrogen receptors ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'BT-20 ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'CD8 ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'chimeric receptor ',weight :2,name: '2'},
{source: 'cytotoxic T lymphocytes ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'cytotoxic T lymphocytes ' ,target: 'Fas ligand ',weight :3,name: '3'},
{source: 'cytotoxic T lymphocytes ' ,target: 'interferon-gamma ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'cytotoxic T lymphocytes ' ,target: 'T47D ',weight :1,name: '1'},
{source: 'DO-1 ' ,target: 'malignant cells ',weight :8,name: '8'},
{source: 'DO-1 ' ,target: 'p53 ',weight :4,name: '4'},
{source: 'DO-1 ' ,target: 'reactive cells ',weight :2,name: '2'},
{source: 'DO-1 ' ,target: 'tumor cells ',weight :2,name: '2'},
{source: 'EGFR ' ,target: 'breast cancer cells ',weight :6,name: '6'},
{source: 'EGFR ' ,target: 'epidermal growth factor receptor ',weight :1,name: '1'},
{source: 'EGFR ' ,target: 'ErbB2 ',weight :11,name: '11'},
{source: 'EGFR ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :2,name: '2'},
{source: 'EGFR ' ,target: 'fibroblasts ',weight :2,name: '2'},
{source: 'EGFR ' ,target: 'Grb2 ',weight :13,name: '13'},
{source: 'EGFR ' ,target: 'GRB2 mRNA ',weight :3,name: '3'},
{source: 'EGFR ' ,target: 'growth factor receptor ',weight :2,name: '2'},
{source: 'EGFR ' ,target: 'MAP kinase ',weight :3,name: '3'},
{source: 'EGFR ' ,target: 'RTKs ',weight :7,name: '7'},
{source: 'endogenous ER ' ,target: 'ER ',weight :3,name: '3'},
{source: 'endogenous ER ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'epidermal growth factor receptor ' ,target: 'EGFR ',weight :3,name: '3'},
{source: 'epidermal growth factor receptor ' ,target: 'ErbB2 ',weight :3,name: '3'},
{source: 'epidermal growth factor receptor ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'Grb2 ',weight :5,name: '5'},
{source: 'epidermal growth factor receptor ' ,target: 'GRB2 mRNA ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'epidermal growth factor receptor ' ,target: 'RTKs ',weight :3,name: '3'},
{source: 'ER ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'ER ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'ER ' ,target: 'CHO ',weight :6,name: '6'},
{source: 'ER ' ,target: 'endogenous ER ',weight :7,name: '7'},
{source: 'ER ' ,target: 'ER-DBD ',weight :9,name: '9'},
{source: 'ER ' ,target: 'ER-responsive reporter gene ',weight :7,name: '7'},
{source: 'ER ' ,target: 'estrogen response element ',weight :1,name: '1'},
{source: 'ER ' ,target: 'MCF-7 ',weight :2,name: '2'},
{source: 'ER ' ,target: 'MCF-7 cells ',weight :11,name: '11'},
{source: 'ER ' ,target: 'OCT ',weight :1,name: '1'},
{source: 'ER ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'ER ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'ER ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'ER ' ,target: 'T47D ',weight :2,name: '2'},
{source: 'ER ' ,target: 'transcriptional activators ',weight :3,name: '3'},
{source: 'ER ' ,target: 'vascular endothelial growth factor ',weight :1,name: '1'},
{source: 'ER ' ,target: 'VEGF ',weight :1,name: '1'},
{source: 'ER ' ,target: 'zinc-finger proteins ',weight :3,name: '3'},
{source: 'ER-DBD ' ,target: 'CHO ',weight :2,name: '2'},
{source: 'ER-DBD ' ,target: 'endogenous ER ',weight :2,name: '2'},
{source: 'ER-DBD ' ,target: 'ER ',weight :11,name: '11'},
{source: 'ER-DBD ' ,target: 'ER-responsive reporter gene ',weight :2,name: '2'},
{source: 'ER-DBD ' ,target: 'MCF-7 cells ',weight :3,name: '3'},
{source: 'ER-responsive reporter gene ' ,target: 'ER ',weight :3,name: '3'},
{source: 'ERalpha ' ,target: 'carcinoma cells ',weight :15,name: '15'},
{source: 'ERalpha ' ,target: 'ERalpha mRNA ',weight :3,name: '3'},
{source: 'ERalpha ' ,target: 'ERbeta ',weight :15,name: '15'},
{source: 'ERalpha ' ,target: 'stromal cells ',weight :1,name: '1'},
{source: 'ERalpha mRNA ' ,target: 'carcinoma cells ',weight :7,name: '7'},
{source: 'ERalpha mRNA ' ,target: 'ERalpha ',weight :9,name: '9'},
{source: 'ERalpha mRNA ' ,target: 'ERbeta ',weight :7,name: '7'},
{source: 'ErbB2 ' ,target: 'breast cancer cells ',weight :5,name: '5'},
{source: 'ErbB2 ' ,target: 'EGFR ',weight :5,name: '5'},
{source: 'ErbB2 ' ,target: 'epidermal growth factor receptor ',weight :1,name: '1'},
{source: 'ErbB2 ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :1,name: '1'},
{source: 'ErbB2 ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'ErbB2 ' ,target: 'Grb2 ',weight :8,name: '8'},
{source: 'ErbB2 ' ,target: 'GRB2 mRNA ',weight :2,name: '2'},
{source: 'ErbB2 ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'ErbB2 ' ,target: 'MAP kinase ',weight :2,name: '2'},
{source: 'ErbB2 ' ,target: 'RTKs ',weight :4,name: '4'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'EGFR ',weight :2,name: '2'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'ErbB2 ',weight :3,name: '3'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'Grb2 ',weight :5,name: '5'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'GRB2 mRNA ',weight :1,name: '1'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'ErbB2 receptor tyrosine kinases ' ,target: 'RTKs ',weight :3,name: '3'},
{source: 'ERbeta ' ,target: 'carcinoma cells ',weight :18,name: '18'},
{source: 'ERbeta ' ,target: 'ERalpha ',weight :21,name: '21'},
{source: 'ERbeta ' ,target: 'ERalpha mRNA ',weight :5,name: '5'},
{source: 'ERbeta ' ,target: 'stromal cells ',weight :1,name: '1'},
{source: 'estradiol receptors ' ,target: 'estrogen receptor sites ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'CHO ',weight :1,name: '1'},
{source: 'Estrogen receptor ' ,target: 'cytosol estrogen receptor ',weight :2,name: '2'},
{source: 'estrogen receptor ' ,target: 'endogenous ER ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'ER ',weight :13,name: '13'},
{source: 'estrogen receptor ' ,target: 'ER-DBD ',weight :2,name: '2'},
{source: 'estrogen receptor ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'Estrogen receptor ' ,target: 'estrogen receptor ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'estrogen response element ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'estrogen receptor ' ,target: 'OCT ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'T47D ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'transcriptional activators ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'vascular endothelial growth factor ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'VEGF ',weight :1,name: '1'},
{source: 'estrogen receptor ' ,target: 'zinc-finger proteins ',weight :1,name: '1'},
{source: 'estrogen receptors alpha and beta ' ,target: 'carcinoma cells ',weight :6,name: '6'},
{source: 'estrogen receptors alpha and beta ' ,target: 'ERalpha ',weight :6,name: '6'},
{source: 'estrogen receptors alpha and beta ' ,target: 'ERalpha mRNA ',weight :2,name: '2'},
{source: 'estrogen receptors alpha and beta ' ,target: 'ERbeta ',weight :6,name: '6'},
{source: 'estrogen receptors alpha and beta ' ,target: 'mRNA ',weight :1,name: '1'},
{source: 'estrogen receptors alpha and beta ' ,target: 'stromal cells ',weight :1,name: '1'},
{source: 'estrogen response element ' ,target: 'CHO ',weight :1,name: '1'},
{source: 'estrogen response element ' ,target: 'endogenous ER ',weight :1,name: '1'},
{source: 'estrogen response element ' ,target: 'ER ',weight :9,name: '9'},
{source: 'estrogen response element ' ,target: 'ER-DBD ',weight :2,name: '2'},
{source: 'estrogen response element ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'estrogen response element ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'estrogen response element ' ,target: 'transcriptional activators ',weight :1,name: '1'},
{source: 'estrogen response element ' ,target: 'zinc-finger proteins ',weight :1,name: '1'},
{source: 'estrogen-receptor ( ER ' ,target: 'progesterone receptor gene promoter ',weight :1,name: '1'},
{source: 'estrogen-receptor ( ER ' ,target: 'promoter regions ',weight :1,name: '1'},
{source: 'estrogen-receptor ( ER ' ,target: 'pS2 ',weight :1,name: '1'},
{source: 'eukaryotic cells ' ,target: 'DNase ',weight :1,name: '1'},
{source: 'Fas ' ,target: 'cytokine ',weight :2,name: '2'},
{source: 'Fas ' ,target: 'Fas ligand ',weight :2,name: '2'},
{source: 'Fas ligand ' ,target: 'cytokine ',weight :3,name: '3'},
{source: 'Fas ligand ' ,target: 'Fas ',weight :4,name: '4'},
{source: 'Fas ligand ' ,target: 'interferon-gamma ',weight :2,name: '2'},
{source: 'FGF8 ' ,target: 'breast cancer cell lines ',weight :2,name: '2'},
{source: 'FGF8 ' ,target: 'FGF family ',weight :3,name: '3'},
{source: 'FGF8 ' ,target: 'FGF8 mRNA ',weight :4,name: '4'},
{source: 'FGF8 ' ,target: 'FGFR1 ',weight :3,name: '3'},
{source: 'FGF8 ' ,target: 'fibroblast growth factor receptor ',weight :3,name: '3'},
{source: 'FGF8 ' ,target: 'fibroblasts ',weight :2,name: '2'},
{source: 'FGF8 ' ,target: 'malignant epithelial cells ',weight :5,name: '5'},
{source: 'FGF8 ' ,target: 'normal epithelial cells ',weight :2,name: '2'},
{source: 'FGF8 ' ,target: 'wnt-1 ',weight :1,name: '1'},
{source: 'FGF8 mRNA ' ,target: 'breast cancer cell lines ',weight :2,name: '2'},
{source: 'FGF8 mRNA ' ,target: 'FGF family ',weight :3,name: '3'},
{source: 'FGF8 mRNA ' ,target: 'FGF8 ',weight :5,name: '5'},
{source: 'FGF8 mRNA ' ,target: 'FGFR1 ',weight :3,name: '3'},
{source: 'FGF8 mRNA ' ,target: 'fibroblast growth factor receptor ',weight :3,name: '3'},
{source: 'FGF8 mRNA ' ,target: 'fibroblasts ',weight :3,name: '3'},
{source: 'FGF8 mRNA ' ,target: 'malignant epithelial cells ',weight :5,name: '5'},
{source: 'FGF8 mRNA ' ,target: 'normal epithelial cells ',weight :2,name: '2'},
{source: 'FGFR1 ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'FGFR1 ' ,target: 'malignant epithelial cells ',weight :1,name: '1'},
{source: 'fibroblast growth factor 8 ' ,target: 'breast cancer cell lines ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'FGF family ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'FGF8 ',weight :6,name: '6'},
{source: 'fibroblast growth factor 8 ' ,target: 'FGF8 mRNA ',weight :6,name: '6'},
{source: 'fibroblast growth factor 8 ' ,target: 'FGFR1 ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'Fibroblast growth factor 8 ',weight :1,name: '1'},
{source: 'fibroblast growth factor 8 ' ,target: 'fibroblast growth factor receptor ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'fibroblasts ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'malignant epithelial cells ',weight :4,name: '4'},
{source: 'fibroblast growth factor 8 ' ,target: 'normal epithelial cells ',weight :2,name: '2'},
{source: 'fibroblast growth factor 8 ' ,target: 'wnt-1 ',weight :2,name: '2'},
{source: 'fibroblast growth factor receptor ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'fibroblast growth factor receptor ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'fibroblast growth factor receptor ' ,target: 'malignant epithelial cells ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'fibroblasts ' ,target: 'EGFR ',weight :2,name: '2'},
{source: 'fibroblasts ' ,target: 'ErbB2 ',weight :3,name: '3'},
{source: 'fibroblasts ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'FGF8 ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'fibroblast growth factor receptor ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'Grb2 ',weight :3,name: '3'},
{source: 'fibroblasts ' ,target: 'GRB2 mRNA ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'malignant epithelial cells ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'fibroblasts ' ,target: 'RTKs ',weight :1,name: '1'},
{source: 'germline ' ,target: 'C-terminal region ',weight :1,name: '1'},
{source: 'germline ' ,target: 'p53 gene ',weight :1,name: '1'},
{source: 'germline ' ,target: 'p73 ',weight :2,name: '2'},
{source: 'germline ' ,target: 'p73 gene ',weight :1,name: '1'},
{source: 'GH3 ' ,target: 'nonpituitary cell line ',weight :1,name: '1'},
{source: 'GH3 ' ,target: 'T47D breast tumor cells ',weight :1,name: '1'},
{source: 'GHRH ' ,target: 'GHRH gene ',weight :3,name: '3'},
{source: 'GHRH ' ,target: 'immunoreactive GHRH ',weight :3,name: '3'},
{source: 'GHRH gene ' ,target: 'immunoreactive GHRH ',weight :1,name: '1'},
{source: 'glucocorticoid receptor ' ,target: 'human breast cancer lines ',weight :2,name: '2'},
{source: 'glucocorticoid receptors ' ,target: 'glucocorticoid receptor ',weight :3,name: '3'},
{source: 'glucocorticoid receptors ' ,target: 'human breast cancer lines ',weight :1,name: '1'},
{source: 'Grb2 ' ,target: 'breast cancer cells ',weight :10,name: '10'},
{source: 'Grb2 ' ,target: 'EGFR ',weight :11,name: '11'},
{source: 'Grb2 ' ,target: 'epidermal growth factor receptor ',weight :1,name: '1'},
{source: 'Grb2 ' ,target: 'ErbB2 ',weight :16,name: '16'},
{source: 'Grb2 ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :1,name: '1'},
{source: 'Grb2 ' ,target: 'fibroblasts ',weight :3,name: '3'},
{source: 'Grb2 ' ,target: 'GRB2 mRNA ',weight :4,name: '4'},
{source: 'Grb2 ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'Grb2 ' ,target: 'MAP kinase ',weight :6,name: '6'},
{source: 'Grb2 ' ,target: 'mitogen-activated protein kinase ',weight :1,name: '1'},
{source: 'Grb2 ' ,target: 'RTKs ',weight :6,name: '6'},
{source: 'GRB2 mRNA ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'GRB2 mRNA ' ,target: 'EGFR ',weight :1,name: '1'},
{source: 'GRB2 mRNA ' ,target: 'ErbB2 ',weight :2,name: '2'},
{source: 'GRB2 mRNA ' ,target: 'Grb2 ',weight :2,name: '2'},
{source: 'GRB2 mRNA ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'growth factor ' ,target: 'cDNA sequence ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'Chinese hamster ovary ( CHO ) cells ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'human breast cancer cell line MCF-7 ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'MCF-7 transfectants ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'growth factor ' ,target: 'transmembrane protein ',weight :1,name: '1'},
{source: 'growth factor receptor ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'growth factor receptor ' ,target: 'EGFR ',weight :2,name: '2'},
{source: 'growth factor receptor ' ,target: 'ErbB2 ',weight :3,name: '3'},
{source: 'growth factor receptor ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'growth factor receptor ' ,target: 'Grb2 ',weight :5,name: '5'},
{source: 'growth factor receptor ' ,target: 'GRB2 mRNA ',weight :1,name: '1'},
{source: 'growth factor receptor ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'growth factor receptor ' ,target: 'RTKs ',weight :1,name: '1'},
{source: 'H460 ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'HeLa cells ' ,target: 'cell line ',weight :2,name: '2'},
{source: 'HeLa cells ' ,target: 'human breast carcinoma cell line ',weight :2,name: '2'},
{source: 'HeLa cells ' ,target: 'human cell lines ',weight :2,name: '2'},
{source: 'HeLa cells ' ,target: 'normal human cell lines ',weight :2,name: '2'},
{source: 'herpes simplex virus thymidine kinase ' ,target: 'beta-gal ',weight :1,name: '1'},
{source: 'herpes simplex virus thymidine kinase ' ,target: 'GH3 ',weight :1,name: '1'},
{source: 'herpes simplex virus thymidine kinase ' ,target: 'nonpituitary cell line ',weight :1,name: '1'},
{source: 'herpes simplex virus thymidine kinase ' ,target: 'T47D breast tumor cells ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'anti-MUC1 antibodies ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'B cells ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'IL-10 ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'IL-4 ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'interleukin-10 ',weight :1,name: '1'},
{source: 'Human B lymphocytes ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'bcl-2 ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'MCF-7 ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'MCF-7 cells ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'p53 mRNA ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'protein tyrosine kinase ',weight :1,name: '1'},
{source: 'human breast adenocarcinoma MCF-7 cells ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'human breast cancer cell line ' ,target: 'cancer cells ',weight :1,name: '1'},
{source: 'human breast cancer cell line ' ,target: 'myoepithelial cells ',weight :1,name: '1'},
{source: 'human breast cancer cell line ' ,target: 'original cell line ',weight :1,name: '1'},
{source: 'human breast cancer cell line ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'human breast cancer cell line MCF-7 ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'human breast cancer cell line MCF-7 ' ,target: 'MCF-7 transfectants ',weight :1,name: '1'},
{source: 'human breast cancer cell line MCF-7 ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'human breast cancer cell lines ' ,target: 'androgen receptors ',weight :1,name: '1'},
{source: 'human breast cancer cell lines ' ,target: 'cell lines ',weight :1,name: '1'},
{source: 'human breast cancer cell lines ' ,target: 'estrogen receptors ',weight :1,name: '1'},
{source: 'human breast cancer cell lines ' ,target: 'MCF ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'AhR ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'estrogen-receptor ( ER ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'n-3 PUFAs ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'progesterone receptor gene promoter ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'promoter regions ',weight :1,name: '1'},
{source: 'human breast cancer cells ' ,target: 'pS2 ',weight :1,name: '1'},
{source: 'human breast cancer lines ' ,target: 'glucocorticoid receptor ',weight :1,name: '1'},
{source: 'human breast carcinoma cell line ' ,target: 'human cell lines ',weight :1,name: '1'},
{source: 'human breast tumor cell lines ' ,target: 'breast tumor cell lines ',weight :2,name: '2'},
{source: 'human breast tumor cell lines ' ,target: 'breast tumor cells ',weight :4,name: '4'},
{source: 'human breast tumor cell lines ' ,target: 'cell lines ',weight :4,name: '4'},
{source: 'human breast tumor cell lines ' ,target: 'phosphatase ',weight :2,name: '2'},
{source: 'human breast tumor cell lines ' ,target: 'Src ',weight :4,name: '4'},
{source: 'human breast tumor cell lines ' ,target: 'Src kinase ',weight :7,name: '7'},
{source: 'human breast tumor cell lines ' ,target: 'tumor cell lines ',weight :2,name: '2'},
{source: 'human breast tumor cell lines ' ,target: 'tyrosine phosphatase ',weight :2,name: '2'},
{source: 'human cancer cells ' ,target: 'beta-galactosidase ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'constitutive promoter ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'NCI-H460 ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'human cancer cells ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'human cells ' ,target: 'cell line ',weight :1,name: '1'},
{source: 'human cells ' ,target: 'HeLa cells ',weight :2,name: '2'},
{source: 'human cells ' ,target: 'human breast carcinoma cell line ',weight :1,name: '1'},
{source: 'human cells ' ,target: 'human cell lines ',weight :1,name: '1'},
{source: 'human cells ' ,target: 'normal human cell lines ',weight :1,name: '1'},
{source: 'IL-10 ' ,target: 'anti-MUC1 antibodies ',weight :1,name: '1'},
{source: 'IL-10 ' ,target: 'IL-4 ',weight :1,name: '1'},
{source: 'IL-10 ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'IL-4 ' ,target: 'anti-MUC1 antibodies ',weight :1,name: '1'},
{source: 'IL-4 ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'interferon-gamma ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'interferon-gamma ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'interferon-gamma ' ,target: 'Fas ligand ',weight :1,name: '1'},
{source: 'interleukin-10 ' ,target: 'anti-MUC1 antibodies ',weight :1,name: '1'},
{source: 'interleukin-10 ' ,target: 'IL-10 ',weight :1,name: '1'},
{source: 'interleukin-10 ' ,target: 'IL-4 ',weight :1,name: '1'},
{source: 'interleukin-10 ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'lung cancer cell lines ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'lung cancer cell lines ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'lymphocytes ' ,target: 'antigens ',weight :1,name: '1'},
{source: 'malignant cells ' ,target: 'DO-1 ',weight :4,name: '4'},
{source: 'malignant cells ' ,target: 'moAB ',weight :1,name: '1'},
{source: 'malignant cells ' ,target: 'monoclonal antibodies ',weight :1,name: '1'},
{source: 'malignant cells ' ,target: 'p53 ',weight :12,name: '12'},
{source: 'malignant cells ' ,target: 'p53 protein ',weight :1,name: '1'},
{source: 'malignant cells ' ,target: 'reactive cells ',weight :5,name: '5'},
{source: 'malignant cells ' ,target: 'tumor cells ',weight :4,name: '4'},
{source: 'malignant epithelial cells ' ,target: 'FGF family ',weight :2,name: '2'},
{source: 'malignant epithelial cells ' ,target: 'FGF8 ',weight :1,name: '1'},
{source: 'malignant epithelial cells ' ,target: 'FGF8 mRNA ',weight :1,name: '1'},
{source: 'malignant epithelial cells ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'malignant epithelial cells ' ,target: 'fibroblast growth factor receptor ',weight :1,name: '1'},
{source: 'malignant epithelial cells ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'MAP kinase ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'MAP kinase ' ,target: 'EGFR ',weight :1,name: '1'},
{source: 'MAP kinase ' ,target: 'ErbB2 ',weight :2,name: '2'},
{source: 'marker gene ' ,target: 'beta-gal ',weight :2,name: '2'},
{source: 'marker gene ' ,target: 'GH3 ',weight :1,name: '1'},
{source: 'marker gene ' ,target: 'herpes simplex virus thymidine kinase ',weight :1,name: '1'},
{source: 'marker gene ' ,target: 'nonpituitary cell line ',weight :1,name: '1'},
{source: 'marker gene ' ,target: 'T47D breast tumor cells ',weight :1,name: '1'},
{source: 'MCF ' ,target: 'androgen receptors ',weight :1,name: '1'},
{source: 'MCF ' ,target: 'estrogen receptors ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'bcl-2 ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'BT-20 ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'chimeric receptor ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'estradiol receptors ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'estrogen receptor sites ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'MCF-7 ' ,target: 'Fas ligand ',weight :3,name: '3'},
{source: 'MCF-7 ' ,target: 'interferon-gamma ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'MCF-7 cells ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'p53 mRNA ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'protein tyrosine kinase ',weight :1,name: '1'},
{source: 'MCF-7 ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'bcl-2 ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'MCF-7 cells ' ,target: 'c-Myc ',weight :8,name: '8'},
{source: 'MCF-7 cells ' ,target: 'CAT ',weight :4,name: '4'},
{source: 'MCF-7 cells ' ,target: 'CHO ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'endogenous ER ',weight :2,name: '2'},
{source: 'MCF-7 cells ' ,target: 'ER ',weight :13,name: '13'},
{source: 'MCF-7 cells ' ,target: 'ER-DBD ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'ER-responsive reporter gene ',weight :2,name: '2'},
{source: 'MCF-7 cells ' ,target: 'P1 promoter ',weight :6,name: '6'},
{source: 'MCF-7 cells ' ,target: 'P1CAT ',weight :2,name: '2'},
{source: 'MCF-7 cells ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'p53 gene ',weight :4,name: '4'},
{source: 'MCF-7 cells ' ,target: 'p53 mRNA ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'protein tyrosine kinase ',weight :1,name: '1'},
{source: 'MCF-7 cells ' ,target: 'serum-stimulated T47D cells ',weight :2,name: '2'},
{source: 'MCF-7 cells ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'MCF-7 transfectants ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'MCF-7 transfectants ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'mitogen-activated protein kinase ' ,target: 'EGFR ',weight :4,name: '4'},
{source: 'mitogen-activated protein kinase ' ,target: 'epidermal growth factor receptor ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'ErbB2 ',weight :4,name: '4'},
{source: 'mitogen-activated protein kinase ' ,target: 'ErbB2 receptor tyrosine kinases ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'Grb2 ',weight :5,name: '5'},
{source: 'mitogen-activated protein kinase ' ,target: 'GRB2 mRNA ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'growth factor receptor ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'MAP kinase ',weight :1,name: '1'},
{source: 'mitogen-activated protein kinase ' ,target: 'RTKs ',weight :3,name: '3'},
{source: 'moAB ' ,target: 'DO-1 ',weight :2,name: '2'},
{source: 'moAB ' ,target: 'malignant cells ',weight :5,name: '5'},
{source: 'moAB ' ,target: 'p53 ',weight :5,name: '5'},
{source: 'moAB ' ,target: 'reactive cells ',weight :1,name: '1'},
{source: 'moAB ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'monoclonal antibodies ' ,target: 'DO-1 ',weight :4,name: '4'},
{source: 'monoclonal antibodies ' ,target: 'malignant cells ',weight :11,name: '11'},
{source: 'monoclonal antibodies ' ,target: 'moAB ',weight :2,name: '2'},
{source: 'monoclonal antibodies ' ,target: 'p53 ',weight :10,name: '10'},
{source: 'monoclonal antibodies ' ,target: 'p53 protein ',weight :1,name: '1'},
{source: 'monoclonal antibodies ' ,target: 'reactive cells ',weight :2,name: '2'},
{source: 'monoclonal antibodies ' ,target: 'tumor cells ',weight :2,name: '2'},
{source: 'mRNA ' ,target: 'carcinoma cells ',weight :6,name: '6'},
{source: 'mRNA ' ,target: 'ERalpha ',weight :6,name: '6'},
{source: 'mRNA ' ,target: 'ERalpha mRNA ',weight :2,name: '2'},
{source: 'mRNA ' ,target: 'ERbeta ',weight :6,name: '6'},
{source: 'mRNA ' ,target: 'stromal cells ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'anti-MUC1 antibodies ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'B cells ',weight :2,name: '2'},
{source: 'MUC1 ' ,target: 'Human B lymphocytes ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'IL-10 ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'IL-4 ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'interleukin-10 ',weight :1,name: '1'},
{source: 'MUC1 ' ,target: 'tumour antigens ',weight :1,name: '1'},
{source: 'n-3 ' ,target: 'human breast cancer cells ',weight :1,name: '1'},
{source: 'n-3 ' ,target: 'n-3 PUFAs ',weight :1,name: '1'},
{source: 'n-3 ' ,target: 'PUFAs ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'beta-galactosidase ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'constitutive promoter ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'NCI-H460 ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'nonpituitary cell line ' ,target: 'T47D breast tumor cells ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'breast cancer cell lines ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'FGF8 ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'FGF8 mRNA ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'fibroblast growth factor receptor ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'normal epithelial cells ' ,target: 'malignant epithelial cells ',weight :2,name: '2'},
{source: 'normal human cell lines ' ,target: 'cell line ',weight :1,name: '1'},
{source: 'normal human cell lines ' ,target: 'human breast carcinoma cell line ',weight :1,name: '1'},
{source: 'normal human cell lines ' ,target: 'human cell lines ',weight :1,name: '1'},
{source: 'NSC-123127 ' ,target: 'NSC-26271 ',weight :1,name: '1'},
{source: 'NSC-123127 ' ,target: 'tumor sites ',weight :1,name: '1'},
{source: 'NSC-26271 ' ,target: 'tumor sites ',weight :1,name: '1'},
{source: 'Oestrogen receptors ' ,target: 'cytoplasmic oestrogen receptors ',weight :1,name: '1'},
{source: 'Oestrogen receptors ' ,target: 'oestrogen receptors ',weight :1,name: '1'},
{source: 'original cell line ' ,target: 'myoepithelial cells ',weight :1,name: '1'},
{source: 'P1 promoter ' ,target: 'breast cancer cells ',weight :4,name: '4'},
{source: 'P1 promoter ' ,target: 'c-Myc ',weight :12,name: '12'},
{source: 'P1 promoter ' ,target: 'c-Myc responsive element ',weight :2,name: '2'},
{source: 'P1 promoter ' ,target: 'CAT ',weight :10,name: '10'},
{source: 'P1 promoter ' ,target: 'chloramphenicol acetyltransferase ',weight :2,name: '2'},
{source: 'P1 promoter ' ,target: 'ER ',weight :5,name: '5'},
{source: 'P1 promoter ' ,target: 'MCF-7 cells ',weight :4,name: '4'},
{source: 'P1 promoter ' ,target: 'P1CAT ',weight :2,name: '2'},
{source: 'P1 promoter ' ,target: 'P1CAT reporter plasmid ',weight :2,name: '2'},
{source: 'P1 promoter ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'P1 promoter ' ,target: 'p53 gene ',weight :10,name: '10'},
{source: 'P1 promoter ' ,target: 'p53 protein ',weight :1,name: '1'},
{source: 'P1 promoter ' ,target: 'serum-stimulated T47D cells ',weight :2,name: '2'},
{source: 'P1CAT ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'P1CAT ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'P1CAT ' ,target: 'ER ',weight :1,name: '1'},
{source: 'P1CAT ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'P1CAT ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'P1CAT reporter plasmid ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'P1CAT reporter plasmid ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'P1CAT reporter plasmid ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'P1CAT reporter plasmid ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'P1CAT reporter plasmid ' ,target: 'ER ',weight :2,name: '2'},
{source: 'P1CAT reporter plasmid ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'P1CAT reporter plasmid ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'P1CAT reporter plasmid ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'P1CAT reporter plasmid ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'P1CAT reporter plasmid ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'bcl-2 ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'p53 ' ,target: 'c-Myc ',weight :5,name: '5'},
{source: 'p53 ' ,target: 'c-Myc responsive element ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'p53 ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'DO-1 ',weight :6,name: '6'},
{source: 'p53 ' ,target: 'ER ',weight :2,name: '2'},
{source: 'p53 ' ,target: 'malignant cells ',weight :18,name: '18'},
{source: 'p53 ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'p53 ' ,target: 'P1 promoter ',weight :4,name: '4'},
{source: 'p53 ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'P1CAT reporter plasmid ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'p53 gene ',weight :4,name: '4'},
{source: 'p53 ' ,target: 'p53 protein ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'protein tyrosine kinase ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'reactive cells ',weight :5,name: '5'},
{source: 'p53 ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'p53 ' ,target: 'tumor cells ',weight :3,name: '3'},
{source: 'p53 gene ' ,target: 'breast cancer cells ',weight :4,name: '4'},
{source: 'p53 gene ' ,target: 'c-Myc ',weight :14,name: '14'},
{source: 'p53 gene ' ,target: 'c-Myc responsive element ',weight :3,name: '3'},
{source: 'p53 gene ' ,target: 'CAT ',weight :15,name: '15'},
{source: 'p53 gene ' ,target: 'chloramphenicol acetyltransferase ',weight :3,name: '3'},
{source: 'p53 gene ' ,target: 'ER ',weight :6,name: '6'},
{source: 'p53 gene ' ,target: 'MCF-7 cells ',weight :6,name: '6'},
{source: 'p53 gene ' ,target: 'P1 promoter ',weight :11,name: '11'},
{source: 'p53 gene ' ,target: 'P1CAT ',weight :3,name: '3'},
{source: 'p53 gene ' ,target: 'P1CAT reporter plasmid ',weight :3,name: '3'},
{source: 'p53 gene ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'p53 gene ' ,target: 'p53 protein ',weight :1,name: '1'},
{source: 'p53 gene ' ,target: 'p73 ',weight :1,name: '1'},
{source: 'p53 gene ' ,target: 'p73 gene ',weight :1,name: '1'},
{source: 'p53 gene ' ,target: 'serum-stimulated T47D cells ',weight :3,name: '3'},
{source: 'p53 mRNA ' ,target: 'bcl-2 ',weight :1,name: '1'},
{source: 'p53 mRNA ' ,target: 'p53 ',weight :1,name: '1'},
{source: 'p53 mRNA ' ,target: 'protein tyrosine kinase ',weight :1,name: '1'},
{source: 'p53 mRNA ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'breast cancer cells ',weight :2,name: '2'},
{source: 'p53 protein ' ,target: 'c-Myc ',weight :5,name: '5'},
{source: 'p53 protein ' ,target: 'c-Myc responsive element ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'CAT ',weight :5,name: '5'},
{source: 'p53 protein ' ,target: 'chloramphenicol acetyltransferase ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'DO-1 ',weight :2,name: '2'},
{source: 'p53 protein ' ,target: 'ER ',weight :2,name: '2'},
{source: 'p53 protein ' ,target: 'malignant cells ',weight :5,name: '5'},
{source: 'p53 protein ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'p53 protein ' ,target: 'moAB ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'monoclonal antibodies ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'P1 promoter ',weight :4,name: '4'},
{source: 'p53 protein ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'P1CAT reporter plasmid ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'p53 ',weight :5,name: '5'},
{source: 'p53 protein ' ,target: 'p53 gene ',weight :4,name: '4'},
{source: 'p53 protein ' ,target: 'reactive cells ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'serum-stimulated T47D cells ',weight :1,name: '1'},
{source: 'p53 protein ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'p73 ' ,target: 'C-terminal region ',weight :3,name: '3'},
{source: 'p73 ' ,target: 'cell lines ',weight :1,name: '1'},
{source: 'p73 ' ,target: 'germline ',weight :3,name: '3'},
{source: 'p73 ' ,target: 'p53 gene ',weight :4,name: '4'},
{source: 'p73 ' ,target: 'p73 gene ',weight :6,name: '6'},
{source: 'p73 ' ,target: 'p73 LOH ',weight :6,name: '6'},
{source: 'p73 gene ' ,target: 'C-terminal region ',weight :1,name: '1'},
{source: 'p73 gene ' ,target: 'germline ',weight :1,name: '1'},
{source: 'p73 gene ' ,target: 'p53 gene ',weight :1,name: '1'},
{source: 'p73 gene ' ,target: 'p73 ',weight :4,name: '4'},
{source: 'p73 gene ' ,target: 'p73 LOH ',weight :2,name: '2'},
{source: 'p73 LOH ' ,target: 'C-terminal region ',weight :2,name: '2'},
{source: 'p73 LOH ' ,target: 'germline ',weight :2,name: '2'},
{source: 'p73 LOH ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'p73 LOH ' ,target: 'p73 ',weight :4,name: '4'},
{source: 'p73 LOH ' ,target: 'p73 gene ',weight :2,name: '2'},
{source: 'pituitary cells ' ,target: 'beta-gal ',weight :2,name: '2'},
{source: 'pituitary cells ' ,target: 'GH3 ',weight :1,name: '1'},
{source: 'pituitary cells ' ,target: 'herpes simplex virus thymidine kinase ',weight :1,name: '1'},
{source: 'pituitary cells ' ,target: 'marker gene ',weight :1,name: '1'},
{source: 'pituitary cells ' ,target: 'nonpituitary cell line ',weight :1,name: '1'},
{source: 'pituitary cells ' ,target: 'T47D breast tumor cells ',weight :1,name: '1'},
{source: 'promoter regions ' ,target: 'progesterone receptor gene promoter ',weight :1,name: '1'},
{source: 'promoter regions ' ,target: 'pS2 ',weight :1,name: '1'},
{source: 'protein tyrosine kinase ' ,target: 'topoisomerase II ',weight :1,name: '1'},
{source: 'pS2 ' ,target: 'progesterone receptor gene promoter ',weight :1,name: '1'},
{source: 'PUFAs ' ,target: 'human breast cancer cells ',weight :1,name: '1'},
{source: 'PUFAs ' ,target: 'n-3 PUFAs ',weight :1,name: '1'},
{source: 'reactive cells ' ,target: 'malignant cells ',weight :1,name: '1'},
{source: 'RTKs ' ,target: 'breast cancer cells ',weight :5,name: '5'},
{source: 'RTKs ' ,target: 'EGFR ',weight :5,name: '5'},
{source: 'RTKs ' ,target: 'ErbB2 ',weight :8,name: '8'},
{source: 'RTKs ' ,target: 'fibroblasts ',weight :2,name: '2'},
{source: 'RTKs ' ,target: 'Grb2 ',weight :12,name: '12'},
{source: 'RTKs ' ,target: 'GRB2 mRNA ',weight :3,name: '3'},
{source: 'RTKs ' ,target: 'growth factor receptor ',weight :2,name: '2'},
{source: 'RTKs ' ,target: 'MAP kinase ',weight :3,name: '3'},
{source: 'serum-stimulated T47D cells ' ,target: 'breast cancer cells ',weight :1,name: '1'},
{source: 'serum-stimulated T47D cells ' ,target: 'c-Myc ',weight :4,name: '4'},
{source: 'serum-stimulated T47D cells ' ,target: 'CAT ',weight :1,name: '1'},
{source: 'serum-stimulated T47D cells ' ,target: 'ER ',weight :2,name: '2'},
{source: 'serum-stimulated T47D cells ' ,target: 'P1 promoter ',weight :3,name: '3'},
{source: 'serum-stimulated T47D cells ' ,target: 'P1CAT ',weight :1,name: '1'},
{source: 'serum-stimulated T47D cells ' ,target: 'p53 gene ',weight :2,name: '2'},
{source: 'Src ' ,target: 'breast tumor cell lines ',weight :1,name: '1'},
{source: 'Src ' ,target: 'breast tumor cells ',weight :3,name: '3'},
{source: 'Src ' ,target: 'cell lines ',weight :2,name: '2'},
{source: 'Src ' ,target: 'human breast tumor cell lines ',weight :2,name: '2'},
{source: 'Src ' ,target: 'phosphatase ',weight :3,name: '3'},
{source: 'Src ' ,target: 'Src kinase ',weight :4,name: '4'},
{source: 'Src ' ,target: 'tumor cell lines ',weight :2,name: '2'},
{source: 'Src ' ,target: 'tyrosine phosphatase ',weight :2,name: '2'},
{source: 'Src kinase ' ,target: 'breast tumor cell lines ',weight :4,name: '4'},
{source: 'Src kinase ' ,target: 'breast tumor cells ',weight :7,name: '7'},
{source: 'Src kinase ' ,target: 'cell lines ',weight :5,name: '5'},
{source: 'Src kinase ' ,target: 'human breast tumor cell lines ',weight :1,name: '1'},
{source: 'Src kinase ' ,target: 'phosphatase ',weight :4,name: '4'},
{source: 'Src kinase ' ,target: 'Src ',weight :8,name: '8'},
{source: 'Src kinase ' ,target: 'tumor cell lines ',weight :4,name: '4'},
{source: 'Src kinase ' ,target: 'tyrosine phosphatase ',weight :4,name: '4'},
{source: 'stromal cells ' ,target: 'carcinoma cells ',weight :5,name: '5'},
{source: 'stromal cells ' ,target: 'ERalpha ',weight :5,name: '5'},
{source: 'stromal cells ' ,target: 'ERalpha mRNA ',weight :2,name: '2'},
{source: 'stromal cells ' ,target: 'ERbeta ',weight :5,name: '5'},
{source: 'T47D ' ,target: 'BT-20 ',weight :1,name: '1'},
{source: 'T47D ' ,target: 'chimeric receptor ',weight :1,name: '1'},
{source: 'T47D ' ,target: 'cytokine ',weight :1,name: '1'},
{source: 'T47D ' ,target: 'Fas ',weight :2,name: '2'},
{source: 'T47D ' ,target: 'Fas ligand ',weight :3,name: '3'},
{source: 'T47D ' ,target: 'interferon-gamma ',weight :1,name: '1'},
{source: 'T47D ' ,target: 'MCF-7 ',weight :2,name: '2'},
{source: 'transcriptional activators ' ,target: 'CHO ',weight :1,name: '1'},
{source: 'transcriptional activators ' ,target: 'endogenous ER ',weight :1,name: '1'},
{source: 'transcriptional activators ' ,target: 'ER ',weight :7,name: '7'},
{source: 'transcriptional activators ' ,target: 'ER-DBD ',weight :2,name: '2'},
{source: 'transcriptional activators ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'transcriptional activators ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'transmembrane protein ' ,target: 'BTC ',weight :2,name: '2'},
{source: 'transmembrane protein ' ,target: 'Chinese hamster ovary ( CHO ) cells ',weight :1,name: '1'},
{source: 'transmembrane protein ' ,target: 'human breast cancer cell line MCF-7 ',weight :1,name: '1'},
{source: 'transmembrane protein ' ,target: 'MCF-7 transfectants ',weight :1,name: '1'},
{source: 'transmembrane protein ' ,target: 'transfected cells ',weight :1,name: '1'},
{source: 'tumor cell lines ' ,target: 'phosphatase ',weight :1,name: '1'},
{source: 'tumor cell lines ' ,target: 'Src ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'beta-galactosidase ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'malignant cells ',weight :2,name: '2'},
{source: 'tumor cells ' ,target: 'myoepithelial cells ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'original cell line ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'p53 ',weight :2,name: '2'},
{source: 'tumor cells ' ,target: 'reactive cells ',weight :1,name: '1'},
{source: 'tumor cells ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'tumor suppressor genes ' ,target: 'BRCA1 ',weight :1,name: '1'},
{source: 'tumor suppressor genes ' ,target: 'BRCA2 ',weight :3,name: '3'},
{source: 'tumor-specific promoter ' ,target: 'beta-galactosidase ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'constitutive promoter ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'H460 ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'human cancer cells ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'lung cancer cell lines ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'NCI-H460 ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'tumor-specific promoter ' ,target: 'tumor cells ',weight :1,name: '1'},
{source: 'tumour suppressor gene ' ,target: 'ATM locus ',weight :2,name: '2'},
{source: 'tumour suppressor gene ' ,target: 'YACs ',weight :2,name: '2'},
{source: 'tyrosine phosphatase ' ,target: 'phosphatase ',weight :1,name: '1'},
{source: 'tyrosine phosphatase ' ,target: 'Src ',weight :1,name: '1'},
{source: 'tyrosine phosphatase ' ,target: 'tumor cell lines ',weight :1,name: '1'},
{source: 'vascular endothelial growth factor ' ,target: 'OCT ',weight :1,name: '1'},
{source: 'vascular endothelial growth factor ' ,target: 'VEGF ',weight :1,name: '1'},
{source: 'VEGF ' ,target: 'OCT ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'breast cancer cell lines ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'FGF family ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'FGF8 ',weight :2,name: '2'},
{source: 'wnt-1 ' ,target: 'FGF8 mRNA ',weight :3,name: '3'},
{source: 'wnt-1 ' ,target: 'FGFR1 ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'fibroblast growth factor receptor ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'fibroblasts ',weight :1,name: '1'},
{source: 'wnt-1 ' ,target: 'malignant epithelial cells ',weight :2,name: '2'},
{source: 'wnt-1 ' ,target: 'normal epithelial cells ',weight :1,name: '1'},
{source: 'YACs ' ,target: 'ATM locus ',weight :1,name: '1'},
{source: 'zinc-finger proteins ' ,target: 'CHO ',weight :1,name: '1'},
{source: 'zinc-finger proteins ' ,target: 'endogenous ER ',weight :1,name: '1'},
{source: 'zinc-finger proteins ' ,target: 'ER ',weight :7,name: '7'},
{source: 'zinc-finger proteins ' ,target: 'ER-DBD ',weight :2,name: '2'},
{source: 'zinc-finger proteins ' ,target: 'ER-responsive reporter gene ',weight :1,name: '1'},
{source: 'zinc-finger proteins ' ,target: 'MCF-7 cells ',weight :2,name: '2'},
{source: 'zinc-finger proteins ' ,target: 'transcriptional activators ',weight :1,name: '1'},

            ]
        }
    ]
};


        myChart.setOption(option); 